site_name: Automate Tasks
repo_name: AnkitApurv/scheduled_login_tradetron
repo_url: https://github.com/AnkitApurv/scheduled_login_tradetron
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - search.share
    - navigation.tracking
    - navigation.indexes
    - navigation.footer
    - toc.follow
plugins:
  - offline
  - search:
      lang: en
  - mkdocstrings
      default_handler: python
        handlers:
          python:
            options:
              show_source: true
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
markdown_extensions:
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      auto_title: true
  - pymdownx.superfences
watch:
  - app
nav:
  - index.md
  - app:
    - app/index.md
    - automate_tasks:
      - app/automate_tasks/index.md
      - tradetron: app/automate_tasks/tradetron.md
    - crypto:
      - app/crypto/index.md
      - crypto_interface: app/crypto/crypto_interface.md
      - read_encrypted_config: app/crypto/read_encrypted_config.md
    - manage_task_secrets:
      - app/manage_task_secrets/index.md
      - create_asymmetric_keyset: app/manage_task_secrets/create_asymmetric_keyset.md
      - tradetron:
        - app/manage_task_secrets/tradetron/index.md
        - add_credentials: app/manage_task_secrets/tradetron/add_credentials.md
        - change_password: app/manage_task_secrets/tradetron/change_password.md
        - auth_user_pywebio: app/manage_task_secrets/tradetron/auth_user_pywebio.md
    - profile:
      - app/profile/index.md
      - tradetron: app/profile/tradetron.md
    - config: app/config.md
    - app_config: app/app_config.md
    - app_utils: app/app_utils.md
    - logging_config: app/logging_config.md
  - logs: logs.md
  - setup: setup.md
  - systemd: systemd.md
  - web_server: web_server.md
extra:
  generator: false
